### ISSUE TITLE
Where is Mysql database File?

### ISSUE THREAD

**Issue by Shahnawaz8980** [mungi1/Restaurant-Android-App#1]

**Comment by iwebnetid** [comment]
yes .. this is a great projects.. sql file is needed too .thank you ...

**Comment by mungwa-agu** [comment]
> yes .. this is a great projects.. sql file is needed too .thank you ...

@iwebnetid I have added the PHP files as requested check in the folder phpFiles. Switch the values to your server details and create sql tables in the database. Let me know if you need further assistance
